"""
embed_cjk_font.py - PlatformIO pre-build extra script

Generates a RISC-V assembly file (src/builtin_fonts_embed.S) that uses
.incbin to embed all builtin epdfont files into .rodata (Flash).
Zero-copy: no RAM allocation for font data.
"""

import os
Import("env")  # type: ignore  # noqa: F821  (PlatformIO SCons global)

PROJECT_DIR = env["PROJECT_DIR"]
ASM_OUT = os.path.join(PROJECT_DIR, "src", "builtin_fonts_embed.S")

# (symbol_prefix, filename_prefix, sizes)
FONTS = [
    ("pretendard", "pretendard", [10, 12, 14]),
    ("kopub",      "kopub",      [10, 12, 14]),
]

lines = ["/* Auto-generated by scripts/embed_cjk_font.py — do not edit */"]
for prefix, fname_prefix, sizes in FONTS:
    for sz in sizes:
        font_src = os.path.join(
            PROJECT_DIR, "lib", "EpdFont", "builtinFonts", f"{fname_prefix}_{sz}.epdfont"
        ).replace(os.sep, '/')
        sym = f"_binary_{prefix}_{sz}_epdfont"
        lines.append(f"""    .section .rodata
    .balign 4
    .global {sym}_start
{sym}_start:
    .incbin "{font_src}"
{sym}_end:
    .global {sym}_end
""")

asm_content = "\n".join(lines) + "\n"

existing = ""
if os.path.exists(ASM_OUT):
    with open(ASM_OUT, "r", encoding="utf-8") as f:
        existing = f.read()

if existing != asm_content:
    with open(ASM_OUT, "w", encoding="utf-8") as f:
        f.write(asm_content)
    print(f"[embed_cjk_font] Generated {ASM_OUT} ({sum(len(s) for _, _, s in FONTS)} fonts)")
else:
    print(f"[embed_cjk_font] {ASM_OUT} is up-to-date")
